name: Sync with Gogs Version, Creates a New Tag
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  ## Runs every day at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:

  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Get the latest version of Gogs
      id: gogs_version
      run: |
        echo ::set-output name=GOGS_VERSION::$(curl -sSL https://api.github.com/repos/gogs/gogs/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GHUB_TOKEN }}
        custom_tag: ${{ steps.gogs_version.outputs.GOGS_VERSION }}